/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */

plugins {
  val kotlin_version = "1.6.21"
  kotlin("jvm") version kotlin_version
  kotlin("plugin.serialization") version kotlin_version
  application
  id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories{
  mavenCentral()
}

dependencies{
  val ktor_version = "2.0.1"
  val logback_version = "1.2.11"
  val spek_version = "2.0.18"
  val sqlite_jdbc_version = "3.36.0.3"
  val ktorm_version = "3.4.1"
  val dotenv_version = "6.2.2"
  val json_version = "1.3.2"
  val kodein_version = "7.10.0"


  implementation("io.ktor:ktor-server-core:$ktor_version")
  implementation("io.ktor:ktor-server-netty:$ktor_version")
  implementation("io.ktor:ktor-server-auth:$ktor_version")
  implementation("io.ktor:ktor-server-default-headers:$ktor_version")
  implementation("io.ktor:ktor-server-status-pages:$ktor_version")

  implementation("ch.qos.logback:logback-classic:$logback_version")

  testImplementation("org.spekframework.spek2:spek-dsl-jvm:$spek_version")
  testRuntimeOnly("org.spekframework.spek2:spek-runner-junit5:$spek_version")
  testImplementation("io.ktor:ktor-server-test-host:$ktor_version")
  testImplementation(kotlin("test"))

  implementation("org.kodein.di:kodein-di-jvm:$kodein_version")
  implementation("org.kodein.di:kodein-di-framework-ktor-server-jvm:$kodein_version")

  implementation("org.xerial:sqlite-jdbc:$sqlite_jdbc_version")
  implementation("org.ktorm:ktorm-core:$ktorm_version")
  implementation("io.github.cdimascio:dotenv-kotlin:$dotenv_version")

  implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$json_version")
  testImplementation("io.ktor:ktor-client-content-negotiation:$ktor_version")
  implementation("io.ktor:ktor-serialization-kotlinx-json:$ktor_version")
  implementation("io.ktor:ktor-server-content-negotiation:$ktor_version")

  implementation("org.flywaydb:flyway-core:8.5.10")
}

application{
  mainClass.set("io.ktor.server.netty.EngineMain")
}

tasks.test {
  useJUnitPlatform{
    includeEngines("spek2")
  }
}